baseURL = "https://hugo-second-site.vercel.app/"
languageCode = "en-us"
theme = "ananke"
title = "SereniTea"
[[menu.main]]
identifier = "products"
name = "products"
pre = "<i class='fa fa-heart'></i>"
url = "/products/"
weight = 1
[[menu.main]]
identifier = "about"
name = "about"
pre = "<i class='fa fa-heart'></i>"
url = "/about/"
weight = 2
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = ""
favicon = ""
featured_image = "/images/feature-image.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = 2
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
